apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fe-pet-battle
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
      description: url of the git repo for the code of deployment
    - name: git-revision
      type: string
      description: revision to be used from repo of the code for deployment
      default: 'master'
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
    - name: build-nodejs
      taskRef:
        name: build-nodejs
        kind: Task
      params:
        - name: NODE_VERSION
          value: nodejs-12
      workspaces:
        - name: source
          workspace: shared-workspace
      runAfter:
        - fetch-repo
